[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "oasis-sapphire-py>=0.4.0",
    "aiohttp",
    "web3",
    "rlp>=3.0.0",
    "trie>=2.0.0",
    "httpx",
    "eth-utils>=5.3.0",
]
